bot:
  name: SchemaRepo
  token: <production_token>

#  name: SchemaRepoTest
#  token: <test_token>
    
  adminChatIds: <admin_chat_ids> #comma separated
  recordsOnPage: 10
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_schemarepo
    driver-class-name: org.postgresql.Driver
    username: schemarepo
    password: schemarepo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
